spring:
  application:
    name: woori-app
  data:
    mongodb:
      uri: mongodb://woori:js8541181!@localhost:27018/woori?authSource=woori

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
